apps/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required
import pam
from apps import login_manager
from apps.authentication.forms import LoginForm

blueprint = Blueprint('authentication_blueprint', __name__)

pam_auth = pam.pam()

class User(UserMixin):
    def __init__(self, username):
        self.id = username

@login_manager.user_loader
def load_user(user_id):
    return User(user_id)

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        if pam_auth.authenticate(username, password):
            user = User(username)
            login_user(user)
            return redirect(url_for('home_blueprint.default'))
        else:
            return render_template('accounts/login.html', form=form, msg='Invalid credentials')
    return render_template('accounts/login.html', form=form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login'))

@blueprint.route('/')
def index():
    return redirect(url_for('authentication_blueprint.login'))

apps/templates/includes/footer.html
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer">
        &copy; WAF for Linux.
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->

apps/templates/includes/navigation.html
<header class="topbar" data-navbarbg="skin6">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin6">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand ms-4" href="/">
                <!-- Logo icon -->
                <b class="logo-icon">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="{{ config.ASSETS_ROOT }}/images/logo-light-icon.png" alt="homepage" class="dark-logo" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="{{ config.ASSETS_ROOT }}/images/logo-light-text.png" alt="homepage" class="dark-logo" />
                </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <a class="nav-toggler waves-effect waves-light text-white d-block d-md-none"
                href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <ul class="navbar-nav d-lg-none d-md-block ">
                <li class="nav-item">
                    <a class="nav-toggler nav-link waves-effect waves-light text-white "
                        href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav me-auto mt-md-0 ">
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
            </ul>

            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav">
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ config.ASSETS_ROOT }}/images/users/1.jpg" alt="user" class="profile-pic me-2">
                        {{ current_user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown"></ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

apps/templates/includes/scripts.html
    <script src="{{ config.ASSETS_ROOT }}/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ config.ASSETS_ROOT }}/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ config.ASSETS_ROOT }}/js/app-style-switcher.js"></script>
    <!--Wave Effects -->
    <script src="{{ config.ASSETS_ROOT }}/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="{{ config.ASSETS_ROOT }}/js/sidebarmenu.js"></script>

apps/templates/includes/sidebar.html
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <!-- User Profile-->
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/home" aria-expanded="false">
                        <i class="mdi me-2 mdi-gauge"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi me-2 mdi-earth"></i>
                        <span class="hide-menu">Input</span>
                    </a>
                    <ul aria-expanded="false" class="collapse first-level">
                        <li class="sidebar-item">
                            <a href="/home/input_status" class="sidebar-link">
                                <i class="mdi mdi-eye"></i>
                                <span class="hide-menu">View Status</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="/home/add_rule" class="sidebar-link">
                                <i class="mdi mdi-plus"></i>
                                <span class="hide-menu">Add Rules</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi me-2 mdi-book-open-variant"></i>
                        <span class="hide-menu">Output</span>
                    </a>
                    <ul aria-expanded="false" class="collapse first-level">
                        <li class="sidebar-item">
                            <a href="/home/output_status" class="sidebar-link">
                                <i class="mdi mdi-eye"></i>
                                <span class="hide-menu">View Status</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="/home/add_rule" class="sidebar-link">
                                <i class="mdi mdi-plus"></i>
                                <span class="hide-menu">Add Rules</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="mdi me-2 mdi-help-circle"></i>
                        <span class="hide-menu">Forward</span>
                    </a>
                    <ul aria-expanded="false" class="collapse first-level">
                        <li class="sidebar-item">
                            <a href="/home/forward_status" class="sidebar-link">
                                <i class="mdi mdi-eye"></i>
                                <span class="hide-menu">View Status</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="/home/add_rule" class="sidebar-link">
                                <i class="mdi mdi-plus"></i>
                                <span class="hide-menu">Add Rules</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ url_for('home_blueprint.view_log') }}" aria-expanded="false">
                        <i class="mdi mdi-file-document"></i>
                        <span class="hide-menu">View Log</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ url_for('home_blueprint.data_visualization') }}" aria-expanded="false">
                        <i class="mdi mdi-file-document"></i>
                        <span class="hide-menu">Data Visualization</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <div class="sidebar-footer">
        <div class="row">
            <div class="col-4 link-wrap">
                <!-- item-->
                <a href="{{ url_for('authentication_blueprint.logout') }}" class="link" data-toggle="tooltip" title="" data-original-title="Logout">
                    <i class="mdi mdi-power"></i>
                </a>
            </div>
        </div>
    </div>
</aside>